apiVersion: v1
kind: Pod
metadata:
  name: satellite-preprocessing
  labels:
    app: redis
spec:
  containers:
    - name: crop
      image: jtrneo/redis:new
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
                    - name: nfs
                      mountPath: "/mnt"
  volumes:
               - name: nfs
                 persistentVolumeClaim:
                  claimName: task-pv-claim
